export default {
  all: "unset",
  userSelect: "none",
  textDecoration: "none",
  "&[data-active]": { color: "$primary", backgroundColor: "$primaryLight" },
  //   color: "$black",
  minWidth: "25%",
  textAlign: "center",
  fontSize: "$lg",
  //   fontWeight: "$bold",
  // fontFamily: "inherit",
  height: "$xl",
  flex: 1,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  color: "$primaryDark",
  backgroundColor: "$primary",
  boxShadow: "$colors$primaryDark -1px -1px 0px 0px",
  //   "&:hover": { color: "$primary", backgroundColor: "$primaryLight" },
}
